"""Entity Representation"""

from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, field_validator, model_validator


class EntitySource(str, Enum):
    """Enumeration of possible sources for entity annotations.

    Attributes:
        GOLD: Human-annotated gold standard entities
        DICTIONARY: Entities matched from biomedical dictionaries
        MODEL: Entities predicted by machine learning models
        AGENT: Entities generated by LLM agents
    """

    GOLD = "GOLD"
    DICTIONARY = "DICTIONARY"
    MODEL = "MODEL"
    AGENT = "AGENT"


class Entity(BaseModel):
    """Pydantic model representing a biomedical named entity.

    Attributes:
        entity_id: Unique identifier for the entity (UUID)
        start_offset: Starting character offset in the source text (0-indexed)
        end_offset: Ending character offset in the source text (exclusive)
        span_text: The actual text span of the entity
        label: The entity label/type (e.g., "DISEASE", "PROTEIN", "COMPLEX")
        source: The source of the entity annotation (EntitySource enum)
        confidence: Optional confidence score between 0.0 and 1.0
        metadata: Optional dictionary containing additional metadata

    Raises:
        ValueError: If end_offset <= start_offset, confidence is out of range,
                    or confidence is missing for MODEL/AGENT sources
    """

    entity_id: UUID = Field(default_factory=uuid4, description="Unique entity identifier")
    start_offset: int = Field(description="Starting character offset in source text (0-indexed)")
    end_offset: int = Field(description="Ending character offset in source text (exclusive)")
    span_text: str = Field(description="The text span of the entity")
    label: str = Field(description="Entity label/type (e.g., 'DISEASE', 'GENE')")
    source: EntitySource = Field(description="Source of the entity annotation")
    confidence: Optional[float] = Field(
        default=None,
        description="Confidence score between 0.0 and 1.0",
    )
    metadata: Optional[dict] = Field(
        default_factory=dict,
        description="Additional metadata dictionary",
    )

    model_config = {"frozen": True, "str_strip_whitespace": True}

    @field_validator("confidence")
    @classmethod
    def validate_confidence_range(cls, v: Optional[float]) -> Optional[float]:
        """Validate that confidence is within valid range [0.0, 1.0]."""
        if v is not None and not (0.0 <= v <= 1.0):
            raise ValueError("confidence must be between 0.0 and 1.0")
        return v

    @model_validator(mode="after")
    def validate_entity(self) -> "Entity":
        """Validate entity constraints that depend on multiple fields."""
        # Validate end_offset > start_offset
        if self.end_offset <= self.start_offset:
            raise ValueError("end_offset must be greater than start_offset")
        
        # Validate confidence is required for MODEL and AGENT sources
        if self.source in (EntitySource.MODEL, EntitySource.AGENT) and self.confidence is None:
            raise ValueError(f"confidence is required when source is {self.source.value}")
        
        return self

    @field_validator("span_text")
    @classmethod
    def validate_span_text_not_empty(cls, v: str) -> str:
        """Validate that span_text is not empty."""
        if not v or not v.strip():
            raise ValueError("span_text cannot be empty")
        return v.strip()


# Explicitly export Entity for imports
__all__ = ["Entity", "EntitySource"]

