from enum import Enum
from pydantic import BaseModel, Field
from uuid import UUID, uuid4
from typing import Optional, Any

class EntitySource(str, Enum):
    """Enumeration of possible sources for entity annotations.

    Attributes:
        GOLD: Human-annotated gold standard entities
        DICTIONARY: Entities matched from biomedical dictionaries
        MODEL: Entities predicted by machine learning models
        AGENT: Entities generated by LLM agents
        RAG: Entities retrieved by RAG models
    """

    GOLD = "GOLD"
    DICTIONARY = "DICTIONARY"
    MODEL = "MODEL"
    AGENT = "AGENT"
    RAG = "RAG"
    OTHER = "OTHER"

class EntityLabel(str, Enum):
    """Enumeration of possible sources for entity labels."

    Attributes:
        Add more entity labels here as needed.
    """

    PROTEIN = "PROTEIN"
    DISEASE = "DISEASE"
    COMPLEX = "COMPLEX"
    FAMILY = "FAMILY"
    GENE = "GENE"
    OTHER = "OTHER"

class Entity(BaseModel):
    """Pydantic model representing a biomedical named entity.

    Attributes:
        entity_id: Unique identifier for the entity (UUID)
        start_offset: Starting character offset in the source text (0-indexed)
        end_offset: Ending character offset in the source text (exclusive)
        span_text: The actual text span of the entity
        label: The entity label/type (e.g., "DISEASE", "PROTEIN", "COMPLEX")
        source: The source of the entity annotation (EntitySource enum)
        confidence: Optional confidence score between 0.0 and 1.0
        metadata: Optional dictionary containing additional metadata

    Raises:
        ValueError: If end_offset <= start_offset, confidence is out of range,
                    or confidence is missing for MODEL/AGENT sources
    """

    entity_id: UUID = Field(default_factory=uuid4, description="Unique entity identifier")
    start_offset: int = Field(description="Starting character offset in source text (0-indexed)")
    end_offset: int = Field(description="Ending character offset in source text (exclusive)")
    span_text: str = Field(description="The text span of the entity")
    ontology_id: Optional[str] = Field(default=None, description="Ontology ID of the entity")
    document_id: Optional[str] = Field(description="Reference to parent document")
    source: EntitySource = Field(description="Source of the entity annotation")
    label: EntityLabel = Field(description="Source of the entity label")
    confidence: Optional[float] = Field(
        default=None,
        description="Confidence score between 0.0 and 1.0",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata dictionary",
    )

    model_version: Optional[str] = Field(default=None, description="Version of the model that generated the entity")
